namespace Picket;

internal static class CliOptionMetadata
{
    internal static string GetArgumentDescription(string command, string syntax)
    {
        string argument = syntax.Trim('<', '>');
        return argument switch
        {
            "path" when command.Equals("picket dir", StringComparison.Ordinal) => "Directory path to scan.",
            "path" => "Filesystem path to scan. Defaults to the current directory when omitted.",
            "repo" => "Git repository to scan. Defaults to the current directory when omitted.",
            "source" => "Source key or path used for cache and rule operations.",
            "report" => "Report file to summarize or open.",
            "rule-id" => "Rule identifier to test.",
            "input" => "Literal sample text scanned by the selected rule.",
            "pre-commit|pre-push|pre-receive|all" => "Hook to install. Defaults to pre-commit when omitted.",
            _ => "Command argument.",
        };
    }

    internal static string GetOptionDescription(string command, string option)
    {
        if (option.Equals("--offline / --live", StringComparison.Ordinal))
        {
            return "Choose local validation or opt-in live provider verification.";
        }

        string key = GetOptionKey(option);
        if (command.Equals("picket revoke github", StringComparison.Ordinal))
        {
            return key switch
            {
                "--allow-non-public-endpoints" => "Allow a guarded GitHub revocation endpoint that resolves to a non-public address.",
                "--confirm-revocation" => "Confirm the irreversible revocation request.",
                "--credential-env" => "Read a credential from this environment variable. Repeat for additional credentials; values never appear in command arguments.",
                "--github-api-endpoint" => "Use this full GitHub credential revocation endpoint instead of https://api.github.com/credentials/revoke.",
                "--github-api-proxy" => "Use this HTTPS proxy for the GitHub credential revocation request.",
                "--timeout" => "Stop waiting for the GitHub revocation response after this many seconds.",
                _ => "GitHub credential revocation option.",
            };
        }

        return key switch
        {
            "--" => "End option parsing before literal input.",
            "-b" => "Load a baseline report and suppress matching findings.",
            "-c" => "Load a config file.",
            "-f" => "Select report format.",
            "-i" => "Load a Gitleaks ignore file.",
            "-l" => "Set the log level.",
            "-r" => "Write a report to this path.",
            "-v" => "Enable verbose logging.",
            "--allow-non-public-endpoints" => "Allow guarded live validation endpoints that are not public internet addresses.",
            "--allow-insecure-source-endpoints" => "Allow HTTP source-host endpoints for trusted local tests or explicitly accepted self-hosted environments; source credentials may be sent in cleartext.",
            "--allow-non-public-source-endpoints" => "Allow source-host endpoints that resolve to private, loopback, link-local, or otherwise non-public addresses.",
            "--azure-blob-container" => "Scan blobs from this Azure Blob Storage container.",
            "--azure-blob-endpoint" => "Use this Azure Blob Storage service endpoint for native object-store enumeration.",
            "--azure-blob-prefix" => "Limit Azure Blob Storage enumeration to blob names with this prefix.",
            "--azure-blob-token-env" => "Read the Azure Blob bearer token or shared access signature from this environment variable.",
            "--azure-blob-token-kind" => "Choose bearer-token authentication or shared access signature query authentication for Azure Blob Storage requests.",
            "--azure-devops-branch" => "Scan this Azure Repos branch.",
            "--azure-devops-build-id" => "Scan artifacts or logs from this Azure Pipelines build ID.",
            "--azure-devops-endpoint" => "Use this Azure DevOps Server or organization endpoint for native source enumeration.",
            "--azure-devops-include-artifacts" => "Include Azure Pipelines build artifact contents in native source enumeration.",
            "--azure-devops-include-logs" => "Include Azure Pipelines build logs in native source enumeration.",
            "--azure-devops-include-release-artifacts" => "Include classic Azure DevOps release build artifact contents in native source enumeration.",
            "--azure-devops-include-wikis" => "Include Azure DevOps wiki backing repositories in native source enumeration.",
            "--azure-devops-max-artifact-megabytes" => "Limit each Azure Pipelines artifact archive download in decimal megabytes; 0 disables the artifact-specific cap.",
            "--azure-devops-max-log-megabytes" => "Limit each Azure Pipelines log download in decimal megabytes; 0 disables the log-specific cap.",
            "--azure-devops-organization" => "Use this Azure DevOps Services organization for native source enumeration.",
            "--azure-devops-project" => "Limit Azure DevOps source enumeration to this project.",
            "--azure-devops-pull-request" => "Scan this Azure Repos pull request source head.",
            "--azure-devops-release-id" => "Scan build artifacts referenced by this classic Azure DevOps release ID.",
            "--azure-devops-repository" => "Limit Azure DevOps source enumeration to this repository.",
            "--azure-devops-token-env" => "Read the Azure DevOps PAT or bearer token from this environment variable.",
            "--azure-devops-token-kind" => "Choose PAT basic authentication or bearer-token authentication for Azure DevOps requests.",
            "--azure-devops-include-packages" => "Include the latest Azure Artifacts NuGet package versions in native source enumeration.",
            "--azure-devops-feed" => "Limit Azure Artifacts package scanning to one feed name or ID.",
            "--azure-devops-package" => "Limit Azure Artifacts package scanning to one exact NuGet package name.",
            "--azure-devops-package-version" => "Scan one exact Azure Artifacts NuGet package version; requires --azure-devops-package.",
            "--azure-devops-max-package-megabytes" => "Set the positive Azure Artifacts package download cap in decimal megabytes; requires package scanning.",
            "--baseline-path" => "Load a baseline report and suppress matching findings.",
            "--baseline-mode" => "Compare baseline findings exactly or treat LF and CRLF evidence as equivalent. Requires a native command or --profile picket.",
            "--bitbucket-api-endpoint" => "Use this Bitbucket Cloud API endpoint for native source enumeration.",
            "--bitbucket-data-center-api-endpoint" => "Use this Bitbucket Data Center REST API endpoint, including its rest/api/1.0 path.",
            "--bitbucket-data-center-project" => "Scan repositories readable in this Bitbucket Data Center project.",
            "--bitbucket-data-center-pull-request" => "Scan this Bitbucket Data Center pull request source head; requires a repository.",
            "--bitbucket-data-center-ref" => "Scan this Bitbucket Data Center branch, tag, or commit.",
            "--bitbucket-data-center-repository" => "Limit Bitbucket Data Center enumeration to this repository slug.",
            "--bitbucket-data-center-token-env" => "Read the Bitbucket Data Center HTTP access token or Basic credential from this environment variable.",
            "--bitbucket-data-center-token-kind" => "Choose bearer-token or Basic authentication for Bitbucket Data Center requests.",
            "--bitbucket-data-center-username-env" => "Read the Bitbucket Data Center username used for Basic authentication from this environment variable.",
            "--bitbucket-include-downloads" => "Scan Bitbucket repository download artifacts.",
            "--bitbucket-include-pipeline-logs" => "Scan Bitbucket pipeline step logs for the selected pipeline.",
            "--bitbucket-include-snippets" => "Scan Bitbucket workspace snippet files.",
            "--bitbucket-pipeline-id" => "Limit Bitbucket pipeline log enumeration to this pipeline ID.",
            "--bitbucket-project" => "Limit Bitbucket workspace repository scans to this project key.",
            "--bitbucket-pull-request" => "Scan this Bitbucket pull request source head.",
            "--bitbucket-ref" => "Scan this Bitbucket branch, tag, or commit.",
            "--bitbucket-repository" => "Scan this Bitbucket repository through native source enumeration.",
            "--bitbucket-token-env" => "Read the Bitbucket source enumeration token or app password from this environment variable.",
            "--bitbucket-token-kind" => "Choose bearer-token authentication or app-password basic authentication for Bitbucket requests.",
            "--bitbucket-username-env" => "Read the Bitbucket username for app-password authentication from this environment variable.",
            "--bitbucket-workspace" => "Scan repositories in this Bitbucket workspace through native source enumeration.",
            "--cache-dir" => "Read or write scanner cache data in this directory.",
            "--cache-mode" => "Choose whether scan cache entries store raw evidence or secret and match hashes only.",
            "--checkpoint" => "Persist encrypted native source-scan progress here and resume it when the source snapshot still matches.",
            "--checkpoint-reset" => "Discard existing checkpoint state before starting the native source scan.",
            "--command" => "Use this command path in generated hook scripts.",
            "--config" => "Load a config file.",
            "--diagnostics" => "Write structured diagnostics for the selected modes.",
            "--diagnostics-dir" => "Write diagnostics artifacts to this directory.",
            "--docker-archive" => "Scan a local Docker image archive produced by docker save.",
            "--enable-rule" => "Enable an additional rule by ID.",
            "--exit-code" => "Exit with this code when findings are present.",
            "--follow-symlinks" => "Follow symlinks while scanning directories.",
            "--force" => "Overwrite existing hook files.",
            "--flow" => "Run the interactive report triage console as inline terminal steps.",
            "--gcs-bucket" => "Scan objects from this Google Cloud Storage bucket.",
            "--gcs-endpoint" => "Use this Google Cloud Storage JSON API endpoint for native object-store enumeration.",
            "--gcs-prefix" => "Limit Google Cloud Storage enumeration to object names with this prefix.",
            "--gcs-token-env" => "Read the Google Cloud Storage OAuth bearer token from this environment variable.",
            "--gcs-user-project" => "Set the requester-pays billing project for Google Cloud Storage requests.",
            "--github-api-endpoint" => "Override the GitHub API endpoint used by live validation and GitHub source enumeration when no source endpoint is supplied.",
            "--github-api-proxy" => "Use this HTTPS proxy for live GitHub API requests.",
            "--github-gist" => "Scan a single GitHub gist by ID.",
            "--github-gists" => "Scan the authenticated user's GitHub gists.",
            "--github-include-actions-artifacts" => "Include GitHub Actions artifact ZIP contents in native source enumeration.",
            "--github-include-issues" => "Include GitHub issue bodies and comments in native source enumeration.",
            "--github-include-releases" => "Include GitHub release bodies and release assets in native source enumeration.",
            "--github-issue-state" => "Filter GitHub issues by state.",
            "--github-organization" => "Scan repositories visible in this GitHub organization through native source enumeration.",
            "--github-pull-request" => "Scan this GitHub pull request head.",
            "--github-ref" => "Scan this GitHub branch, tag, or commit.",
            "--github-repository" => "Scan this GitHub repository through native source enumeration.",
            "--github-repository-type" => "Filter organization or user repository listings by GitHub type.",
            "--github-source-api-endpoint" => "Use this GitHub API endpoint for native source enumeration.",
            "--github-token-env" => "Read the GitHub source enumeration token from this environment variable.",
            "--github-user" => "Scan public repositories for this GitHub user through native source enumeration.",
            "--github-user-gists" => "Scan public GitHub gists for this user.",
            "--gitea-api-endpoint" => "Use this Gitea API endpoint for native source enumeration.",
            "--gitea-actions-run-id" => "Limit Gitea Actions artifact scanning to this run ID.",
            "--gitea-generic-package-file" => "Limit Gitea generic package scanning to this file.",
            "--gitea-generic-package-name" => "Limit Gitea generic package scanning to this package name.",
            "--gitea-generic-package-owner" => "Scan Gitea generic package files owned by this user or organization.",
            "--gitea-generic-package-version" => "Limit Gitea generic package scanning to this package version.",
            "--gitea-include-actions-artifacts" => "Include Gitea Actions artifact ZIP contents in native source enumeration.",
            "--gitea-include-issues" => "Include Gitea issue bodies and comments in native source enumeration.",
            "--gitea-include-releases" => "Include Gitea release notes and assets in native source enumeration.",
            "--gitea-issue-state" => "Filter Gitea issues by state.",
            "--gitea-organization" => "Scan repositories in this Gitea organization.",
            "--gitea-pull-request" => "Scan this Gitea pull request source head.",
            "--gitea-ref" => "Scan this Gitea branch, tag, or commit.",
            "--gitea-repository" => "Scan this Gitea repository through native source enumeration.",
            "--gitea-token-env" => "Read the Gitea source enumeration token from this environment variable.",
            "--gitea-user" => "Scan repositories owned by this Gitea user.",
            "--gitlab-api-endpoint" => "Use this GitLab API endpoint for native source enumeration.",
            "--gitlab-group" => "Scan projects in this GitLab group through native source enumeration.",
            "--gitlab-include-job-artifacts" => "Include GitLab job artifact archives in native source enumeration.",
            "--gitlab-include-job-logs" => "Include GitLab job trace logs in native source enumeration.",
            "--gitlab-include-packages" => "Include GitLab generic package files in native source enumeration.",
            "--gitlab-include-subgroups" => "Include projects from GitLab subgroups when scanning a group.",
            "--gitlab-include-snippets" => "Include GitLab project snippets in native source enumeration.",
            "--gitlab-merge-request" => "Scan this GitLab merge request source head.",
            "--gitlab-pipeline-id" => "Limit GitLab job log and artifact enumeration to this pipeline ID.",
            "--gitlab-project" => "Scan this GitLab project path or numeric project ID through native source enumeration.",
            "--gitlab-ref" => "Scan this GitLab branch, tag, or commit.",
            "--gitlab-token-env" => "Read the GitLab source enumeration token from this environment variable.",
            "--gitleaks-ignore-path" => "Load a Gitleaks ignore file.",
            "--ignore-gitleaks-allow" => "Do not honor gitleaks:allow comments.",
            "--ignore-path" => "Load additional ignore patterns from this file.",
            "--input" => "Read a portable cache archive from this path.",
            "--live" => "Run opt-in live provider verification for supported findings.",
            "--live-provider-rate-limit-ms" => "Set the minimum milliseconds between live requests to the same provider. Use 0 to disable.",
            "--live-rate-limit-ms" => "Set the minimum milliseconds between live provider requests across all providers. Use 0 to disable.",
            "--live-tls-mode" => "Choose the TLS policy for live provider requests.",
            "--log-level" => "Set the log level.",
            "--log-opts" => "Pass git log options for compatibility scans.",
            "--max-archive-depth" => "Limit nested archive traversal depth.",
            "--max-archive-entries" => "Limit files extracted from each archive.",
            "--max-archive-megabytes" => "Limit uncompressed archive size.",
            "--max-archive-ratio" => "Limit archive expansion ratio.",
            "--max-decode-depth" => "Limit recursive decoding passes.",
            "--max-target-megabytes" => "Skip files larger than this size.",
            "--no-banner" => "Suppress the startup banner.",
            "--no-color" => "Disable colored console output.",
            "--no-git" => "Scan a filesystem source instead of git history through the deprecated detect shim.",
            "--no-ignore" => "Do not apply ignore files.",
            "--offline" => "Run local structural validation without contacting providers.",
            "--oci-archive" => "Scan a local OCI image-layout archive.",
            "--older-than-days" => "Prune cache entries older than this age.",
            "--only-verified" => "Keep structurally-valid offline findings and active live-verification findings.",
            "--open" => "Open an HTML report in the default browser.",
            "--other-keys" => "Prune cache entries for config or source keys other than the selected key.",
            "--output" => "Write a portable cache archive to this path.",
            "--path" => "Set the synthetic path used for sample input.",
            "--pipe" => "Read standard input through the deprecated detect shim.",
            "--platform" => "Set compatibility platform metadata.",
            "--pre-commit" => "Scan the pre-commit diff range.",
            "--print-config" => "Print the resolved config.",
            "--profile" => "Use the named rule/profile mode.",
            "--redact" => "Redact secret text in reports. n is the percent to hide: 0 shows secrets, 100 writes REDACTED, and 75 keeps about the first 25%.",
            "--registry-auth-endpoint" => "Use this explicitly trusted cross-host bearer-token service instead of the registry challenge realm.",
            "--registry-endpoint" => "Override the OCI Distribution API endpoint derived from the image reference.",
            "--registry-image" => "Scan this OCI or Docker registry image reference, including Docker Hub shorthand.",
            "--registry-max-image-megabytes" => "Limit aggregate unique manifest, config, and layer downloads for the image in decimal megabytes.",
            "--registry-password-env" => "Read the registry password or personal access token for basic authentication from this environment variable.",
            "--registry-platform" => "Scan only this os/architecture[/variant] image from a multi-platform index; all platforms are scanned when omitted.",
            "--registry-token-env" => "Read a pre-issued registry bearer token from this environment variable.",
            "--registry-username-env" => "Read the registry username for basic authentication from this environment variable.",
            "--repo" => "Install hook scripts into this repository.",
            "--report-format" => "Select report format.",
            "--report-path" => "Write a report to this path.",
            "--report-template" => "Render template reports with this template file.",
            "--results" => "Keep findings with the selected validation result states.",
            "--rule-pack" => "Add an opt-in built-in rule pack. Values: picket-strict or picket-experimental. Repeat to add both.",
            "--s3-access-key-id-env" => "Read the S3 access key ID from this environment variable.",
            "--s3-bucket" => "Scan objects from this S3 bucket.",
            "--s3-endpoint" => "Use this S3 or S3-compatible endpoint for native object-store enumeration.",
            "--s3-prefix" => "Limit S3 enumeration to object keys with this prefix.",
            "--s3-region" => "Use this AWS region for S3 SigV4 request signing.",
            "--s3-secret-access-key-env" => "Read the S3 secret access key from this environment variable.",
            "--s3-session-token-env" => "Read the optional S3 session token from this environment variable.",
            "--scan" => "Open the native scan workspace instead of loading an existing report.",
            "--source" => "Override the source label stored in findings and fingerprints.",
            "--staged" => "Scan staged changes.",
            "--timeout" => "Stop scanning after this many seconds. Use 0 to disable.",
            "--verify" => "Run opt-in live provider verification for supported findings.",
            "--verbose" => "Enable verbose logging.",
            _ => command.Length == 0 ? "Command option." : "Command-specific option.",
        };
    }

    private static string GetOptionKey(string option)
    {
        string key = option.Split(" / ", StringSplitOptions.None)[0];
        int valueSeparator = key.IndexOf(' ', StringComparison.Ordinal);
        return valueSeparator > 0 ? key[..valueSeparator] : key;
    }
}
